# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the remaining application code
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose port if needed (not specified for MCP)

# Default command to run the MCP server
CMD [ "node", "dist/index.js" ]
